title: Titanic - Machine Learning project
email: fertmeneses@gmail.com
logo: assets/00_Titanic_FM_summary.png
description:  A python project made for the Kaggle competition "Titanic - Machine Learning from Disaster", by Fernando Meneses.
show_downloads: True
google_analytics: G-HHCL9E8VP6
theme: jekyll-theme-minimal
